services:
  clash-merger:
    image: ghcr.io/socialyjj/clash-sub-merger:latest
    container_name: submerger
    restart: unless-stopped
    ports:
      - "8666:8666"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
