"""
Templates API
Template management endpoints
"""
import os
import time
from typing import Optional, List, Dict
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel, Field

from core.dependencies import verify_session
from core.database import load_config, update_config
from helpers import handle_api_errors, generate_timestamp_id
from logger_config import get_logger

logger = get_logger(__name__)
router = APIRouter()

# Get paths from environment or default
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.environ.get('DATA_DIR', os.path.join(BASE_DIR, 'data'))
YAML_SOURCE_DIR = os.path.join(DATA_DIR, 'uploads')
OUTPUT_FILE = os.path.join(DATA_DIR, 'myconfig.yaml')


# ==================== Built-in Template ====================

def get_builtin_template():
    """Get the built-in default template"""
    return {
        'id': 'builtin',
        'name': '内置模板',
        'header': '''# Clash/Mihomo Configuration
# Generated by SubMerger

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback:
    - https://1.1.1.1/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
''',
        'suffix': '''
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,节点选择
''',
        'proxy_groups': [
            {
                'name': '节点选择',
                'type': 'select',
                'proxies': ['{{ALL_PROXIES}}'],
                '_editable': True,
                '_icon': '🚀',
                '_description': '手动选择节点'
            },
            {
                'name': '自动选择',
                'type': 'url-test',
                'proxies': ['{{ALL_PROXIES}}'],
                'url': 'http://www.gstatic.com/generate_204',
                'interval': 300,
                '_editable': True,
                '_icon': '⚡',
                '_description': '自动测速选择最快节点'
            }
        ],
        'builtin': True
    }


# ==================== Data Models ====================

class CreateTemplate(BaseModel):
    name: str = Field(min_length=1, max_length=100)
    header: str = ""
    suffix: str = ""
    proxy_groups: Optional[List[dict]] = None


class UpdateTemplate(BaseModel):
    name: Optional[str] = Field(None, max_length=100)
    header: Optional[str] = None
    suffix: Optional[str] = None
    proxy_groups: Optional[List[dict]] = None
    content: Optional[str] = None  # Legacy format support


class TemplateContent(BaseModel):
    content: str
    file_aliases: Optional[Dict[str, str]] = None


# ==================== API Endpoints ====================

@router.get("")
@handle_api_errors
def list_templates(_: bool = Depends(verify_session)):
    """List all templates"""
    config = load_config()
    templates = config.get('templates', [])
    
    # Add is_builtin flag to custom templates
    for template in templates:
        if 'is_builtin' not in template:
            template['is_builtin'] = False
        if 'is_modified' not in template:
            template['is_modified'] = False
    
    # Add builtin template to the list
    builtin = get_builtin_template()
    builtin['is_builtin'] = True
    builtin['is_modified'] = 'builtin_template_override' in config
    
    return {"templates": [builtin] + templates}


@router.get("/builtin")
@handle_api_errors
def get_builtin_template_endpoint(_: bool = Depends(verify_session)):
    """Get built-in template"""
    config = load_config()
    template = get_builtin_template()
    
    # Apply override if exists
    override = config.get('builtin_template_override', {})
    if override:
        if 'header' in override:
            template['header'] = override['header']
        if 'suffix' in override:
            template['suffix'] = override['suffix']
        if 'proxy_groups' in override:
            template['proxy_groups'] = override['proxy_groups']
    
    return {"template": template}


@router.get("/{template_id}")
@handle_api_errors
def get_template(template_id: str, _: bool = Depends(verify_session)):
    """Get template by ID"""
    config = load_config()
    
    if template_id == 'builtin':
        template = get_builtin_template()
        # Apply override if exists
        override = config.get('builtin_template_override', {})
        if override:
            if 'header' in override:
                template['header'] = override['header']
            if 'suffix' in override:
                template['suffix'] = override['suffix']
            if 'proxy_groups' in override:
                template['proxy_groups'] = override['proxy_groups']
        return {"template": template}
    
    for template in config.get('templates', []):
        if template['id'] == template_id:
            return {"template": template}
    
    raise HTTPException(status_code=404, detail="Template not found")


@router.post("")
@handle_api_errors
def create_template(data: CreateTemplate, _: bool = Depends(verify_session)):
    """Create a new template"""
    def add_template(config: dict) -> dict:
        template_id = generate_timestamp_id('tpl_')
        template = {
            'id': template_id,
            'name': data.name,
            'header': data.header,
            'suffix': data.suffix,
            'proxy_groups': data.proxy_groups or [],
            'created_at': int(time.time())
        }
        config.setdefault('templates', []).append(template)
        return dict(template)

    template = update_config(add_template)
    
    return {"status": "success", "template": template}


@router.put("/{template_id}")
@handle_api_errors
def update_template(template_id: str, data: UpdateTemplate, _: bool = Depends(verify_session)):
    """Update a template"""
    # Handle legacy content format
    if data.content is not None:
        # Split content into header, proxy_groups, and suffix
        import yaml
        try:
            from yaml import CLoader as YAMLLoader
        except ImportError:
            from yaml import Loader as YAMLLoader
        
        try:
            parsed = yaml.load(data.content, Loader=YAMLLoader)
            if isinstance(parsed, dict):
                # Extract proxy-groups if present
                proxy_groups = parsed.get('proxy-groups', [])
                
                # Remove proxy-groups from parsed to get header
                if 'proxy-groups' in parsed:
                    del parsed['proxy-groups']
                
                # Find where rules start (this becomes suffix)
                content_lines = data.content.split('\n')
                rules_index = -1
                for i, line in enumerate(content_lines):
                    if line.strip().startswith('rules:'):
                        rules_index = i
                        break
                
                if rules_index >= 0:
                    header = '\n'.join(content_lines[:rules_index]).strip()
                    suffix = '\n'.join(content_lines[rules_index:]).strip()
                else:
                    # No rules section, treat everything before proxy-groups as header
                    pg_index = -1
                    for i, line in enumerate(content_lines):
                        if line.strip().startswith('proxy-groups:'):
                            pg_index = i
                            break
                    if pg_index >= 0:
                        header = '\n'.join(content_lines[:pg_index]).strip()
                        suffix = ''
                    else:
                        header = data.content.strip()
                        suffix = ''
                
                data.header = header
                data.suffix = suffix
                data.proxy_groups = proxy_groups
        except:
            # If parsing fails, treat as plain header
            data.header = data.content
            data.suffix = ''
            data.proxy_groups = []
    
    def apply_template_update(config: dict) -> dict:
        if template_id == 'builtin':
            # Update builtin template override
            override = config.get('builtin_template_override', {})
            if data.header is not None:
                override['header'] = data.header
            if data.suffix is not None:
                override['suffix'] = data.suffix
            if data.proxy_groups is not None:
                override['proxy_groups'] = data.proxy_groups
            config['builtin_template_override'] = override
            return dict(override)

        for template in config.get('templates', []):
            if template['id'] == template_id:
                if data.name is not None:
                    template['name'] = data.name
                if data.header is not None:
                    template['header'] = data.header
                if data.suffix is not None:
                    template['suffix'] = data.suffix
                if data.proxy_groups is not None:
                    template['proxy_groups'] = data.proxy_groups
                return dict(template)

        raise HTTPException(status_code=404, detail="Template not found")

    template = update_config(apply_template_update)
    return {"status": "success", "template": template}


@router.delete("/{template_id}")
@handle_api_errors
def delete_template(template_id: str, _: bool = Depends(verify_session)):
    """Delete a template"""
    if template_id == 'builtin':
        raise HTTPException(status_code=400, detail="Cannot delete builtin template")

    def remove_template(config: dict):
        templates = config.get('templates', [])
        config['templates'] = [t for t in templates if t['id'] != template_id]

    update_config(remove_template)
    
    return {"status": "success"}


@router.post("/builtin/reset")
@handle_api_errors
def reset_builtin_template(_: bool = Depends(verify_session)):
    """Reset builtin template to default"""
    def reset_builtin_override(config: dict):
        # Remove builtin template override
        config.pop('builtin_template_override', None)

    update_config(reset_builtin_override)
    
    return {"status": "success", "message": "Builtin template reset to default"}


@router.post("/{template_id}/duplicate")
@handle_api_errors
def duplicate_template(template_id: str, _: bool = Depends(verify_session)):
    """Duplicate a template"""
    def duplicate_existing_template(config: dict) -> dict:
        if template_id == 'builtin':
            source = get_builtin_template()
            # Apply override if exists
            override = config.get('builtin_template_override', {})
            if override:
                if 'header' in override:
                    source['header'] = override['header']
                if 'suffix' in override:
                    source['suffix'] = override['suffix']
                if 'proxy_groups' in override:
                    source['proxy_groups'] = override['proxy_groups']
        else:
            source = next((t for t in config.get('templates', []) if t['id'] == template_id), None)
            if not source:
                raise HTTPException(status_code=404, detail="Template not found")

        new_id = generate_timestamp_id('tpl_')
        new_template = {
            'id': new_id,
            'name': f"{source.get('name', 'Template')} (Copy)",
            'header': source.get('header', ''),
            'suffix': source.get('suffix', ''),
            'proxy_groups': source.get('proxy_groups', []),
            'created_at': int(time.time())
        }
        config.setdefault('templates', []).append(new_template)
        return dict(new_template)

    new_template = update_config(duplicate_existing_template)
    
    return {"status": "success", "template": new_template}


@router.post("/preview")
@handle_api_errors
def preview_template(data: TemplateContent, _: bool = Depends(verify_session)):
    """Preview template merge result"""
    from services.config_merger import ConfigMerger
    
    try:
        merger = ConfigMerger(
            yaml_dir=YAML_SOURCE_DIR,
            output_file=OUTPUT_FILE,
            custom_header=data.content,
            file_aliases=data.file_aliases or {}
        )
        result = merger.merge()
        return {"status": "success", "preview": result[:5000]}
    except Exception as e:
        return {"status": "error", "error": str(e)}
